### ISSUE TITLE
Registering an addin

### ISSUE THREAD

**Issue by pssguy** [rstudio/addinexamples#4]
I have created my very first package which has a single function which adds a few lines of code that I want to avoid having to retype regularly, very similar to the 'Insert %in%' example. When the package is loaded locally and I run the function, it works smoothly 

I want to have it available in RStudio as an addin

From https://rstudio.github.io/rstudioaddins/ 

I need to "Create a file at inst/rstudio/addins.dcf"

But am not sure how to do this. I have no problem creating a local addins.dcf  but then what....

**Comment by pssguy** [comment]
Answered [here](https://support.rstudio.com/hc/en-us/community/posts/208887987-Registering-Addins?page=1#community_comment_210498288)

**Comment by gjclaxton** [comment]
the answer link is gone
