### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by jangorecki** [rstudio/addinexamples#5]
last sentence from readme
`See this support article for more details.` points to https://support.rstudio.com/hc/en-us/articles/215605467 which is `oops The page you were looking for doesn't exist`

**Comment by kevinushey** [comment]
Thanks! We now link to the [RStudio Addins](http://rstudio.github.io/rstudioaddins/) website, which is our primary landing point for introduction to addins.

**Comment by jangorecki** [comment]
@kevinushey good to see you. We very just discussing [here](https://github.com/Rdatatable/data.table/issues/1524). There is an issue which would be good for RStudio to be aware of.
