### ISSUE TITLE
Reformat R code

### ISSUE THREAD

**Issue by caleblareau** [rstudio/addinexamples#7]
In the comment chunks that RStudio interprets when compiling a notebook, running the reformat code makes the chunk options not function correctly. 

e.g.
# \+ fig.width=16, fig.height=5, message = FALSE, warning = FALSE, echo=FALSE

goes to 
'# + fig.width=16, fig.height=5, message = FALSE, warning = FALSE,
'# echo=FALSE

(without the ') which is not ideal

**Comment by kevinushey** [comment]
This would be an issue in the [formatr](https://github.com/yihui/formatR) package (which the addin uses behind the scenes to power reformatting) -- can you please file an issue there?
